// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddConnection(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['AddConnection'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function AddConnectionGroup(arg1) {
  return window['go']['main']['App']['AddConnectionGroup'](arg1);
}

export function ApplyUpdate(arg1) {
  return window['go']['main']['App']['ApplyUpdate'](arg1);
}

export function AssignUngroupedToGroup(arg1) {
  return window['go']['main']['App']['AssignUngroupedToGroup'](arg1);
}

export function BrowseConnectionDir(arg1, arg2) {
  return window['go']['main']['App']['BrowseConnectionDir'](arg1, arg2);
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function CloseSession(arg1) {
  return window['go']['main']['App']['CloseSession'](arg1);
}

export function DeleteConnectionGroupByName(arg1) {
  return window['go']['main']['App']['DeleteConnectionGroupByName'](arg1);
}

export function DismissSponsorSlot(arg1, arg2) {
  return window['go']['main']['App']['DismissSponsorSlot'](arg1, arg2);
}

export function DownloadFromRemote(arg1, arg2, arg3) {
  return window['go']['main']['App']['DownloadFromRemote'](arg1, arg2, arg3);
}

export function ExportConnections(arg1) {
  return window['go']['main']['App']['ExportConnections'](arg1);
}

export function FlushAnalytics() {
  return window['go']['main']['App']['FlushAnalytics']();
}

export function GetAnalyticsEnabled() {
  return window['go']['main']['App']['GetAnalyticsEnabled']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetConnectionHome(arg1) {
  return window['go']['main']['App']['GetConnectionHome'](arg1);
}

export function GetInstallID() {
  return window['go']['main']['App']['GetInstallID']();
}

export function GetRemoteHome(arg1) {
  return window['go']['main']['App']['GetRemoteHome'](arg1);
}

export function GetSessionSysInfo(arg1) {
  return window['go']['main']['App']['GetSessionSysInfo'](arg1);
}

export function GetSponsorConfig(arg1) {
  return window['go']['main']['App']['GetSponsorConfig'](arg1);
}

export function ImportConnections() {
  return window['go']['main']['App']['ImportConnections']();
}

export function IsProLicensed() {
  return window['go']['main']['App']['IsProLicensed']();
}

export function ListActiveSessions() {
  return window['go']['main']['App']['ListActiveSessions']();
}

export function ListConnectionGroups(arg1) {
  return window['go']['main']['App']['ListConnectionGroups'](arg1);
}

export function ListConnections(arg1, arg2) {
  return window['go']['main']['App']['ListConnections'](arg1, arg2);
}

export function ListRemoteDir(arg1, arg2) {
  return window['go']['main']['App']['ListRemoteDir'](arg1, arg2);
}

export function MkdirRemote(arg1, arg2) {
  return window['go']['main']['App']['MkdirRemote'](arg1, arg2);
}

export function MoveConnection(arg1, arg2) {
  return window['go']['main']['App']['MoveConnection'](arg1, arg2);
}

export function OpenLocalFolder(arg1) {
  return window['go']['main']['App']['OpenLocalFolder'](arg1);
}

export function PickDownloadDir() {
  return window['go']['main']['App']['PickDownloadDir']();
}

export function PickLocalDir() {
  return window['go']['main']['App']['PickLocalDir']();
}

export function PickLocalFile() {
  return window['go']['main']['App']['PickLocalFile']();
}

export function PickSaveFile(arg1) {
  return window['go']['main']['App']['PickSaveFile'](arg1);
}

export function ReadRemoteFile(arg1, arg2) {
  return window['go']['main']['App']['ReadRemoteFile'](arg1, arg2);
}

export function RefreshSponsorConfig() {
  return window['go']['main']['App']['RefreshSponsorConfig']();
}

export function RemoveRemote(arg1, arg2) {
  return window['go']['main']['App']['RemoveRemote'](arg1, arg2);
}

export function RenameConnectionGroup(arg1, arg2) {
  return window['go']['main']['App']['RenameConnectionGroup'](arg1, arg2);
}

export function RenameConnectionGroupByName(arg1, arg2) {
  return window['go']['main']['App']['RenameConnectionGroupByName'](arg1, arg2);
}

export function RenameRemote(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenameRemote'](arg1, arg2, arg3);
}

export function ResizeSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeSession'](arg1, arg2, arg3);
}

export function SendSessionInput(arg1, arg2) {
  return window['go']['main']['App']['SendSessionInput'](arg1, arg2);
}

export function SetAnalyticsEnabled(arg1) {
  return window['go']['main']['App']['SetAnalyticsEnabled'](arg1);
}

export function SetDeleted(arg1, arg2) {
  return window['go']['main']['App']['SetDeleted'](arg1, arg2);
}

export function StartSession(arg1) {
  return window['go']['main']['App']['StartSession'](arg1);
}

export function TrackSponsorEvent(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['TrackSponsorEvent'](arg1, arg2, arg3, arg4, arg5);
}

export function TransferBetweenServers(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['TransferBetweenServers'](arg1, arg2, arg3, arg4);
}

export function TransferToConnection(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['TransferToConnection'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateConnection(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['UpdateConnection'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function UploadToRemote(arg1, arg2, arg3) {
  return window['go']['main']['App']['UploadToRemote'](arg1, arg2, arg3);
}

export function WriteRemoteFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['WriteRemoteFile'](arg1, arg2, arg3);
}
