// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddConnection(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['AddConnection'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function CloseSession(arg1) {
  return window['go']['main']['App']['CloseSession'](arg1);
}

export function ListConnections(arg1, arg2) {
  return window['go']['main']['App']['ListConnections'](arg1, arg2);
}

export function SendSessionInput(arg1, arg2) {
  return window['go']['main']['App']['SendSessionInput'](arg1, arg2);
}

export function SetDeleted(arg1, arg2) {
  return window['go']['main']['App']['SetDeleted'](arg1, arg2);
}

export function StartSession(arg1) {
  return window['go']['main']['App']['StartSession'](arg1);
}
