// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';

export function AddConnection(arg1:string,arg2:string,arg3:number,arg4:string,arg5:string,arg6:string,arg7:boolean):Promise<string>;

export function CloseSession(arg1:string):Promise<void>;

export function ListConnections(arg1:boolean,arg2:string):Promise<Array<db.Connection>>;

export function SendSessionInput(arg1:string,arg2:string):Promise<void>;

export function SetDeleted(arg1:string,arg2:boolean):Promise<void>;

export function StartSession(arg1:string):Promise<string>;
