// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {sftpclient} from '../models';
import {main} from '../models';
import {db} from '../models';

export function AddConnection(arg1:string,arg2:string,arg3:number,arg4:string,arg5:string,arg6:string,arg7:boolean):Promise<string>;

export function BrowseConnectionDir(arg1:string,arg2:string):Promise<Array<sftpclient.RemoteEntry>>;

export function CloseSession(arg1:string):Promise<void>;

export function DismissSponsorSlot(arg1:string,arg2:number):Promise<void>;

export function DownloadFromRemote(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GetConnectionHome(arg1:string):Promise<string>;

export function GetRemoteHome(arg1:string):Promise<string>;

export function GetSessionSysInfo(arg1:string):Promise<main.SysInfo>;

export function GetSponsorConfig(arg1:boolean):Promise<main.SponsorConfigView>;

export function IsProLicensed():Promise<boolean>;

export function ListActiveSessions():Promise<Array<main.SessionInfo>>;

export function ListConnections(arg1:boolean,arg2:string):Promise<Array<db.Connection>>;

export function ListRemoteDir(arg1:string,arg2:string):Promise<Array<sftpclient.RemoteEntry>>;

export function MkdirRemote(arg1:string,arg2:string):Promise<void>;

export function OpenLocalFolder(arg1:string):Promise<void>;

export function PickDownloadDir():Promise<string>;

export function PickLocalDir():Promise<string>;

export function PickLocalFile():Promise<string>;

export function PickSaveFile(arg1:string):Promise<string>;

export function ReadRemoteFile(arg1:string,arg2:string):Promise<string>;

export function RefreshSponsorConfig():Promise<main.SponsorConfigView>;

export function RemoveRemote(arg1:string,arg2:string):Promise<void>;

export function RenameRemote(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ResizeSession(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SendSessionInput(arg1:string,arg2:string):Promise<void>;

export function SetDeleted(arg1:string,arg2:boolean):Promise<void>;

export function StartSession(arg1:string):Promise<string>;

export function TransferBetweenServers(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function TransferToConnection(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function UpdateConnection(arg1:string,arg2:string,arg3:string,arg4:number,arg5:string,arg6:string,arg7:string,arg8:boolean):Promise<void>;

export function UploadToRemote(arg1:string,arg2:string,arg3:string):Promise<void>;

export function WriteRemoteFile(arg1:string,arg2:string,arg3:string):Promise<void>;
